version: '2'

services:
  db:
    image: postgres:15.1
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data/

  api:
    build: api
    env_file:
      - .env
    image: hivecv/lumber-hub-api:latest
    ports:
      - 80:80