"""empty message

Revision ID: 89ab786fd909
Revises: b28d2f1723e3
Create Date: 2023-03-02 23:19:32.728890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ab786fd909'
down_revision = 'b28d2f1723e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('msg', sa.String(), nullable=True),
    sa.Column('args', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('levelname', sa.String(), nullable=True),
    sa.Column('levelno', sa.Integer(), nullable=True),
    sa.Column('pathname', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('exc_info', sa.String(), nullable=True),
    sa.Column('exc_text', sa.String(), nullable=True),
    sa.Column('stack_info', sa.String(), nullable=True),
    sa.Column('lineno', sa.Integer(), nullable=True),
    sa.Column('funcName', sa.String(), nullable=True),
    sa.Column('created', sa.Float(), nullable=True),
    sa.Column('msecs', sa.Float(), nullable=True),
    sa.Column('relativeCreated', sa.Float(), nullable=True),
    sa.Column('thread', sa.BigInteger(), nullable=True),
    sa.Column('threadName', sa.String(), nullable=True),
    sa.Column('processName', sa.String(), nullable=True),
    sa.Column('process', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
