"""empty message

Revision ID: b28d2f1723e3
Revises: b81c331e8b86
Create Date: 2023-02-25 20:09:43.003715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28d2f1723e3'
down_revision = 'b81c331e8b86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('last_active', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_active')
    # ### end Alembic commands ###
